package com.dcc.osheaapp.common.exception;

public enum ErrorCode {
  GENERAL,
  NOT_FOUND,
  INVALID_TOKEN,
  NOT_SAVED,
  EXPIRED_TOKEN,
  EXPIRED_REFRESH_TOKEN,
  NOT_LOGGED_IN,
  OUTLET_STATE_TOGGLE_ERROR,
  ALREADY_EXIST,
  OUTLET_ALREADY_MAPPED,
  MULTIPLE_BA_TO_OUTLET,
  BA_NOT_MAPPED_TO_OUTLET,

  TARGET_INVALID_BA,
  TARGET_INVALID_ACTIVE_BA,
  INVALID_MULTIPLE_OUTLET_ASSOCIATION,
  INVALID_EXCEL_FILE,
  FILE_NOT_FOUND,
  INACTIVE_OUTLET_ASSOCIATION,

  INVALID_FILE_NAME,
  FILE_COULD_NOT_BE_STORED,
  ERROR_CREATING_DIRECTORY,
  ERROR_COPYING_FILE,
  ERROR_READING_FILE,
  FILE_COULD_NOT_BE_FETCHED,
  INVALID_FILE_PATH_SEQUENCE, // Added for path traversal attempts
  ERROR_GENERATING_REPORT;
}
