package com.dcc.osheaapp.report.common.model;

public enum ReportType {
    ATTENDANCE_SUMMARY, SALE_PURCHASE , SALE, PURCHASE, COUNTER_STOCK, ATTENDANCE_DETAILS, BA_PERFORMANCE, BA_RANK, PRIMARY_CATEGORY_ANALYSIS, SECONDARY_CATEGORY_ANALYSIS, DISTRIBUTOR, OUTLET, USER;
}
