springdoc.swagger-ui.config-url=/ismsapi/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/ismsapi/v3/api-docs
#

#spring.datasource.url=jdbc:mysql://dccdevprojects.csxf38glfvmf.ap-south-1.rds.amazonaws.com:3306/osheadb?useSSL=false
#spring.datasource.username=dradmin
#spring.datasource.password=drlifestar#01

spring.datasource.url=jdbc:mysql://dccdevprojects.csxf38glfvmf.ap-south-1.rds.amazonaws.com/dcc_secondary_sales
#spring.datasource.url=jdbc:mysql://ojb-test-db.c63aobvmsnnu.ap-south-1.rds.amazonaws.com/ojb_prod_bck_3rd_may

spring.datasource.username=dradmin
spring.datasource.password=drlifestar#01


file.productUploadFolder=/opt/imageFolder/product/
file.soSelfieUploadFolder=/opt/imageFolder/soselfie/
file.selfieUploadFolder=/opt/imageFolder/selfie/
file.invoiceUploadFolder=/opt/imageFolder/invoice/
file.outletUploadFolder=/opt/imageFolder/outlet/


ba.userCount=671




spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
#spring.jackson.time-zone=Asia/Kolkata