info.app.name=PFM API Hub Security
info.app.description=Spring Boot project for PFM API Hub Security Application
info.app.version=1.0.0

application-description=@project.description@
application-version=@project.version@
logging.level.org.springframework.boot.autoconfigure=ERROR

server.port=9092
spring.main.allow-circular-references=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

## ApiHub DB - JPA - windows authentication
spring.user.datasource.driver-class-name=com.mysql.jdbc.Driver
security.oauth2.resource.filter-order=3

#spring.jpa.generate-ddl: true
#spring.jpa.show-sql=false
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.properties.hibernate.cache.use_second_level_cache: false
#spring.jpa.properties.hibernate.cache.use_query_cache: false


#added for system variable - SD
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
jwt.refresh-token.validity=86400000

spring.messages.basename=messages

file.fileUploadFolder=D:/Documents/Oshea/FileUpload/

spring.web.resources.static-locations=file:D:/Documents/Oshea/FileUpload/

# spring.profiles.active=dccdev
 spring.profiles.active=uat
#spring.profiles.active=prod
